### ISSUE TITLE
Issue avec Paul

### ISSUE THREAD

**Issue by Ojdp** [Ojdp/toolboxojdp#1]
Askip j'ai une issue avec toi Paul à propos de get_one_file_size()

**Comment by PaulMalliet** [comment]
assigne moi dans ce cas

**Comment by Ojdp** [comment]
il faut qu'on améliore get_one_file_size(), pour qu’elle renvoie en plus, l’extension du fichier dans le data.frame. (file_ext()).

**Comment by PaulMalliet** [comment]
Ca m'a l'air bien propre tout ca

**Comment by PaulMalliet** [comment]
mais ce serait effectivement mieux avec l'extension du fichier. Tu sais ce qu'il te reste à faire championne ;)
